### ISSUE TITLE
Exception java.lang.AssertionError Message: expected [FAILED] but found [SUCCESS]Stacktrace:

### ISSUE THREAD

**Issue by akhilreddy92** [opengeospatial/ets-sta10#55]
androidUniversalReleaseProtectedNoProtectedKeys
(from com.kony.appfactory.test.singletenant.android.AndroidChannelTest took 4 min 36 sec)
FAIL

Exception java.lang.AssertionError
Message: expected [FAILED] but found [SUCCESS]Stacktrace:

	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at com.kony.appfactory.test.singletenant.android.AndroidChannelTest.androidUniversalReleaseProtectedNoProtectedKeys(AndroidChannelTest.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

getting like this any idea please?

**Comment by hylkevds** [comment]
The class `com.kony.appfactory.test.singletenant.android.AndroidChannelTest` is not part of this project. Why are you asking this question here?

**Comment by dstenger** [comment]
@akhilreddy92 Maybe, you accidentaly posted this in the wrong issue tracker? Can you please close the issue if this is the case?
